### ISSUE TITLE
Doorbell Feature Request

### ISSUE THREAD

**Issue by v1027m** [UbhiTS/ad-alexadoorbell#2]
First off, thank you making this app. I've had something similar to this in NodeRed running on my server, and it has always been a little slower than I would like. Appd fixes this.

The only thing I'm missing from my setup before is an actual "physical" button to act as a doorbell.
I like having the old school option for someone to push a button (like a zigbee or zwave one) and then the announcement goes off. Sometimes the motion sensor will give me a false positive and having the button eliminates that.

If you could add that in this app that would be great. (Wish I could figure out python so I could build these apps on my own)

Again thanks for your work.

**Comment by UbhiTS** [comment]
Hi, thank you so much for appreciation :) ... so can you please explain the workflow in brief. Do you want the button to be like a master override switch that would set off the doorbell ?

**Comment by v1027m** [comment]
Yes, a master override is exactly what I mean.
In the case where my motion sensor did not detect someone. 

Or entirely removing the dependency on the motion sensor and allowing a "button/switch" entity to be the only trigger.

I'm not sure if that's asking a lot, but do appreciate your efforts.

**Comment by UbhiTS** [comment]
Sure, I'll integrate it over the weekend. Would that work? or do you need it sooner ?

**Comment by v1027m** [comment]
Whenever you have time to get to it works for me, afterall you are helping me out.

Thank you for implementing this feature.

**Comment by UbhiTS** [comment]
Hi, can you take the latest update v1.0.9 and please test it. Please check the updated readme for the configuration variable for the doorbell

**Comment by UbhiTS** [comment]
closing due to no response

**Comment by danielo515** [comment]
So it is possible to use just a door sensor rather than a motion sensor?
